### ISSUE TITLE
Is there any way to move the arrow to the right hand side?

### ISSUE THREAD

**Issue by joshrobertson92** [amsik/liquor-tree#100]
Is there any way to move the arrow to the right hand side, as when the tree is expanding i'm running out of width?

![image](https://user-images.githubusercontent.com/45604375/51316218-dfbbb180-1a4b-11e9-9f2f-01e57306cb6d.png)

**Comment by amsik** [comment]
Hi! Please check:

https://github.com/amsik/liquor-tree/issues/62

**Comment by joshrobertson92** [comment]
Thanks 👍
