### ISSUE TITLE
Unable to expand or select a node on Safari Fullscreen Mode

### ISSUE THREAD

**Issue by GillesChila** [amsik/liquor-tree#108]
Hi, 

Got the following issue when using LiquorTree under Safari and ONLY in fullscreen mode (by adding a shortcut of the app to the homescreen).

When running under Safari AND in Fullscreen mode ==>

- The tree displays correctly
- I am still able to filter nodes
- I CANNOT expand nodes (nothing happens when clicking)
- I CANNOT select a node (nothing happens when clicking)

**Comment by GillesChila** [comment]
After testing and to give more details on this strange issue 

- When using Safari in normal browser mode : nodes can be expanded or selected by a single mouse click (or single touch on mobile device)

- When using Safari in webapp/fullscreen mode : a double mouse click or double touch is required to expand or select nodes.

Why ????

**Comment by amsik** [comment]
Hi. Do you have some error in the console?

**Comment by GillesChila** [comment]
No idea of what happens behind the screen since i am NOT able to remote debug Safari on iOS, i do not own a Mac to do so.

If there is any solution to remote debug Safari on iPhone or Ipad from a Windows PC, please let me know and i'll do the for you in order to check if there is any console error or message regarding this issue.

Rgds

**Comment by amsik** [comment]
I have tested on iPhone... and it works. 

Can you test it on the blank page without dependencies? You can take an example from `demo/pages/filtering.html`.

**Comment by GillesChila** [comment]
The tree is embedded in a Tabpane coming from Quasar (vueJS) framework.

I'll check if the problem is due to a potential conflit between this component and LiquorTree and will let you know.

Regards

**Comment by GillesChila** [comment]
This problem is solved with new Quasar Version (1.0)

It is not related to LiquorTree, i close this issue
