### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by amsik** [amsik/liquor-tree#11]

**Comment by Diaskhan** [comment]
1.I guesse there must be state of node! Draggable !
Later write another ideas !

**Comment by amsik** [comment]
Yeah, I agree. I have some ideas and 'druggable' is also there.

**Comment by Diaskhan** [comment]
The second one is ability to transfer nodes from one tree to another !

**Comment by Diaskhan** [comment]
third ability there must be flag of node **AllowDrop**
In scenario of folders The file item could not be droped in the files.
**The files for this scenerio could be dropped only in folders !**

![image](https://user-images.githubusercontent.com/15046677/38766562-5538d2da-3ff5-11e8-8b29-3a9981a7abdf.png)
