### ISSUE TITLE
Show ONLY nodes that have a checked state by adding an external check button

### ISSUE THREAD

**Issue by mustafahamid** [amsik/liquor-tree#110]
Hi, 
 Is there an event in the liquor tree that shows only that show ONLY nodes that have bee checked state

**Comment by amsik** [comment]
Hi.
Please check [the API](https://amsik.github.io/liquor-tree/#Filtering). It will help you.

**Comment by mustafahamid** [comment]
@amsik 
thank you, but I need to show  ONLY nodes that have a checked state.

**Comment by amsik** [comment]
```javascript
{
  matcher(query, node) {
    return node.checked()
  }
}
```

**Comment by mustafahamid** [comment]
@amsik  thank you, 
 But how to call this matcher by using a check button? 
I imagine an example: 
```
   <tree
                :data="Data"
                :onlychecked'='true' 
                :filter="Filter"
                :options="treeOptions2" />
```

**Comment by amsik** [comment]
You can find exaples on the link I sent (JSFiddle snippet)

**Comment by mustafahamid** [comment]
@amsik the problem is that I need to apply two matcher s on the same tree:
The first one is triggered by input text HTML.
The second one is triggered by a check button.

**Comment by amsik** [comment]
You can change **filter** property to uniq value. It will apply filter.
