### ISSUE TITLE
Drag & drop: not possible to drop nodes in the same position

### ISSUE THREAD

**Issue by kiril-malyhin** [amsik/liquor-tree#117]
Hi all,

Currently, even on demo page (https://amsik.github.io/liquor-tree/#Drag-amp-Drop) you can't move different nodes for example on first position multiple times. I think it is a bug.

Steps to reproduce: 

- Move "LOOSE TYPING in first position". You will get such view.

![image](https://user-images.githubusercontent.com/11473999/56569294-5c1cde00-65c1-11e9-939f-d3cae7940462.png)

- Try to move "ANONYMOYS FUNCTIONS" on first position - error.

![image](https://user-images.githubusercontent.com/11473999/56569364-81115100-65c1-11e9-89d1-cddbb57d390f.png)

p.s. I was able to manage it only via re-render tree.

**Comment by amsik** [comment]
Hi. Yeah, it is a bug. I'll try fix it as soon as possible

**Comment by kiril-malyhin** [comment]
@amsik , do you have any updates with this issue?

**Comment by kiril-malyhin** [comment]
Hey, @amsik , do you have any news? :)

**Comment by kiril-malyhin** [comment]
@ncharalampidis , it works, thanks!
