### ISSUE TITLE
Checkbox and async data

### ISSUE THREAD

**Issue by fsanzv** [amsik/liquor-tree#120]
Hi.

I'm trying to load async data using `isBatch` and `fetchData`, everything working fine. Now in the received data I must to check some of the fetched rows. I'm doing it adding to them: `state: { checked: true }` and the checked children shows correctly with the check but the parents doesn't get the checked or indeterminate state automatically.

Can the parents states be properly updated in some way? I'm doing with a recursive function called from the `tree:data:received` event but this seems very complicated to me.

**Comment by amsik** [comment]
Hi.

This is fixed in the new version (0.2.56). Please check

**Comment by fsanzv** [comment]
Thank you very much!

It is working fine now. I have a doubt regarding checked elements but I'll open a new Issue.
