### ISSUE TITLE
Tree re-render

### ISSUE THREAD

**Issue by GreatGui** [amsik/liquor-tree#126]
If I use async data and also the method of re-rendering (this. $ Refs.tree.setModel (newData)). when I re-render Async stops working
with the following message

Error in v-on handler: "TypeError: Can not set property 'loading' of undefined"

**Comment by amsik** [comment]
Hi. You probably have an incorrect node(s) in `newData` (I mean node's format)

**Comment by GreatGui** [comment]
I did an example
Async stops working after using the Re-render

https://codepen.io/GreatGui/pen/mYjpvJ

**Comment by amsik** [comment]
I've fixed the error. Fixed in @0.2.57 version

Vuejs is not do re-rendering for nodes with **the same id**. For your example you have to change node's id to different ones or leave them empty

**Comment by GreatGui** [comment]
Thank you!
