### ISSUE TITLE
doubleclick on childs ?

### ISSUE THREAD

**Issue by Diaskhan** [amsik/liquor-tree#13]
Amsik it possible to generate doubleclick event when we double-clicking childs ?

I got the scenario when I double-clicked to 1111111 or 2222222 (see screenshot)
It must return data by ajax call and render it in red zone!

![image](https://user-images.githubusercontent.com/15046677/38852716-b97e7288-423c-11e8-9e06-acc4316b56a8.png)

**Comment by amsik** [comment]
I have added the `node:dblclick` event.

Example:

```html
<template>
  <tree :data="someData" @node:dblclick="onDblClick">
</template>
<script>
  export default {
   data() => ({
     someData: []
   }),
   methods: {
     onDblClick(node) {  }
   }
  }
</script>
```

**Comment by amsik** [comment]
Yes. I know. But I don't have time now :(  
I will add to the documentation all events and more examples within few days. 
And also I will update a CDN version and you can use it in a few minutes :)
