### ISSUE TITLE
Parent and children with attributes for text with different names

### ISSUE THREAD

**Issue by florianojunior** [amsik/liquor-tree#130]
Hello,

I mount a Liquor Tree with a list of class "Object1".

"Object1" has an attribute named "name", everything works perfectly because I define:
...
treeOptions: {
                     propertyNames: {
                         text: 'name',
                         children: 'getChildrensMethodName',
                     }
                 }
...

My problem is that my childrens list returns a list of the "Object2" class, and the "name" attribute does not exist in it, it's a different name.

Is there a way to use Liquor Tree in this way?

Thanks

**Comment by amsik** [comment]
Hi. No, it is not possible. You need to convert the object to the correct names.

**Comment by florianojunior** [comment]
> Hi. No, it is not possible. You need to convert the object to the correct names.

Thank you very much for your clarification.
