### ISSUE TITLE
Consider the cases when DnD callbacks return Promise

### ISSUE THREAD

**Issue by become-iron** [amsik/liquor-tree#132]
For example, it might be useful when checking for `onDragFinish` is performed on backend side

**Comment by amsik** [comment]
It’s not very good when a user waits for something ... you can go to ondragFinish: cancel the action, make a server call and if everything is ok, use https://amsik.github.io/liquor-tree/#Tree-append-criteria -node method.

**Comment by become-iron** [comment]
Yeah, that would be much better
