### ISSUE TITLE
Cannot read property '$on' of undefined

### ISSUE THREAD

**Issue by breekoy** [amsik/liquor-tree#136]
I'm having a hard time catching tree events. I followed your docs (https://amsik.github.io/liquor-tree/#Events) but somehow didn't work for me and returned an error that says **"Cannot read property '$on' of undefined"** at this line: 

`this.$refs.tree.$on(e.name, this.someMethod(e))`

Really appreciate your help. :)

**Comment by amsik** [comment]
Hi! Could you please show me the full list of code/component?

**Comment by breekoy** [comment]
Hello, here's the code: https://gist.github.com/breekoy/38046eb4882425c5b685efd6673b0a3e

**Comment by amsik** [comment]
Sorry, but I'm not able to reproduce :( 
Can you share a real code via https://codesandbox.io ?

**Comment by become-iron** [comment]
@breekoy 
Did you try to call `this.$nextTick` in the first place? It might be that the tree is not mounted yet in the moment, when you try to get it

**Comment by breekoy** [comment]
@become-iron No, I just followed what's in the docs (https://amsik.github.io/liquor-tree/#Events). There's no `this.$nextTick` in there. Anyway, where should I call `this.$nextTick` in order for me to try.

**Comment by become-iron** [comment]
For example, this way:

```js
mounted () {
    this.$nextTick(() => {
        treeEventsList.forEach(e => {
            this.$refs.tree.$on(e.name, e => {
                console.log(e)
            })
        })
    })
}
```

And of course read what nextTick is at all: 

- https://vuejs.org/v2/api/#vm-nextTick
- https://vuejsdevelopers.com/2019/01/22/vue-what-is-next-tick/

**Comment by breekoy** [comment]
@become-iron @amsik  

I tried calling `this.$nextTick` on `mounted()` hook but no luck. However, I tried to put it inside the `updated()` hook and luckily it works. 

This would do for me. Thanks for your help. :+1:

**Comment by become-iron** [comment]
@breekoy 
`updated` hook is being called multiple times. So it's not the right solution
I suggest you to find out why tree-component is mounting late or try to set listeners after some small delay

**Comment by become-iron** [comment]
@breekoy
I think your problem doesn't relate to this component itself

**Comment by dongfang0-0** [comment]
@breekoy I hove a same question, for now I also use updated with debounce, I also use the timeout function, the problem is that the mounted function is invoked before the tree loaded, when add a breakpoint at the mounted function, the tree state is loading
I guess in the vue, the tree is load in aync way, not sync ! but now didn't have found the root cause...
If somebody fix this, notify me, 3ks.

**Comment by breekoy** [comment]
> the problem is that the mounted function is invoked before the tree loaded

> I guess in the vue, the tree is load in aync way, not sync !

Yes, this is what apparently is happening. In my case, I have 300+ objects coming from an API to be loaded to the tree component. I had the API call on the `created()` hook thinking that it would be fine. However, when the `mounted()` hook is invoked, tree is still loading. My guesses would be the API didn't respond yet when `mounted()` is invoked or the objects to be loaded are huge enough to cause delay in mounting/loading the tree component. 

I somehow made this work by creating an async method that calls the API and call that method inside the `mounted()` hook with `.then()` chained into it. Inside the function parameter of `then()`, I called the `this.$refs.tree.setModel()` and `this.$refs.tree.$on()`. 

Like this:

```vue
<tree id="tree" ref="tree" :data="tree_data"></tree>

<script>
    import Tree from 'liquor-tree'

    export default {
        components: { Tree },
        data () {
            return { tree_data: [] }
        },
        methods: {
            async getObjectsFromApi () {
                let response = await someApiCallMethod()
                return response.data
            }
        },
        mounted () {
            this.getObjectsFromApi().then(tree_data => {
                  this.tree_data = tree_data
                  this.$refs.tree.setModel(this.tree_data)
                  this.$refs.tree.$on('node:selected', event => {
                      //some code here to handle the event...
                  })
            })
        },
        beforeDestroy () {
            //making sure tree_data is empty before leaving the page
            this.tree_data = []
            this.$refs.tree.setModel(this.tree_data)
        }
    }
</script>
```

sorry for a very late response, been kinda busy lately.

**Comment by become-iron** [comment]
@breekoy 
Or you could just create the tree only after obtaining of data:

```vue
<tree v-if="data.length" :data="tree_data" @node:selected="handleNodeSelect"></tree>
```
