### ISSUE TITLE
Duplication of nodes on drag-on-drop

### ISSUE THREAD

**Issue by become-iron** [amsik/liquor-tree#139]
The way to reproduce:
1) drag and drop some node
2) dragged node has duplicate

Could be tested even in DnD example: https://jsfiddle.net/amsik/h1z2n05k

As I noticed this bug appeared in the last version (0.2.60)

**Comment by saeidjoker** [comment]
I've checked this with version 0.2.60 and the bug even appears on the demo.
This error only occurs for root nodes
Here's a screenshot:
![image](https://user-images.githubusercontent.com/20520614/61996086-aa041f00-b0a5-11e9-8c2c-c1f5c1ad0f3f.png)

**Comment by saeidjoker** [comment]
I've checked this and the error occurs on 0.2.60.
The error can be reproduced in demos: https://amsik.github.io/liquor-tree/#Drag-amp-Drop
![image](https://user-images.githubusercontent.com/20520614/61996102-e0da3500-b0a5-11e9-8b4e-1625c8341164.png)

**Comment by saeidjoker** [comment]
I found the line that causes this problem in DndMixing.js file in initDragListeners method and in onMouseUp local method. The line is this:

`this.draggableNode.node.state('dragging', false)`

**Comment by Codebreaker101** [comment]
The problem still persist even after the #140 fix

**Comment by hawezo** [comment]
The issue is still there. https://i.imgur.com/d8icfsO.gifv

**Comment by Codebreaker101** [comment]
In a situation with 3 nodes without children the situation is as follows
On startDragging@Node.js the model has 3 nodes and each node has parent = null
On finishDragging@Node.js the model has 3 nodes and the dragged node has parent equals to the destination on all 3 destinationPosition types

Will investigate further.

**Comment by Codebreaker101** [comment]
[This line](https://github.com/amsik/liquor-tree/blob/44ab87f2d4d7248cd1d282163d130a5342ba2bb2/src/mixins/DndMixin.js#L162) adds destination node as parent node. It was added here 25516dbe3008c72480f32f7df223e71d56270f61. Cant find context for why was it added but after removing this line everything seems to work

**Comment by saiat3** [comment]
> [This line](https://github.com/amsik/liquor-tree/blob/44ab87f2d4d7248cd1d282163d130a5342ba2bb2/src/mixins/DndMixin.js#L162) adds destination node as parent node. It was added here [25516db](https://github.com/amsik/liquor-tree/commit/25516dbe3008c72480f32f7df223e71d56270f61). Cant find context for why was it added but after removing this line everything seems to work

Thanks! I was diving deeper into the code for more than 4 hours trying to fix following issue, until I bumped into your solution. Did fix it for me. Hope they sort out this issue asap.

**Comment by amsik** [comment]
Hi! Fixed. Please update to the new version.

**Comment by Codebreaker101** [comment]
Working great!
I think this issue can be closed.

**Comment by amsik** [comment]
Done
