### ISSUE TITLE
Set a different property name for children

### ISSUE THREAD

**Issue by kayakinwunmi** [amsik/liquor-tree#14]
Thanks for this amazing Library!

I do not have control over the JSON data from the server. Is it possible to have an option set a different property name for children objects like below?

`const treeData = [
  { text: 'Item 1', state: { visible: false } },
  { text: 'Item 2', state: { selected: 
  { text: 'Item 3', children: [
    { label: 'Item 3.1', state: { disabled: true } },
    { label: 'Item 3.2', state: { selectable: false } }
  ]}
  // and so on ...
]`

Thanks

**Comment by Diaskhan** [comment]
Yes liqur allow this.  read docs.
https://amsik.github.io/liquor-tree/#Redefine-Structure-Example

**Comment by kayakinwunmi** [comment]
Thanks @Diaskhan
