### ISSUE TITLE
How to add a custom element in node spans?

### ISSUE THREAD

**Issue by undergroundwires** [amsik/liquor-tree#143]
I'd like to be able to add image(s) with link and hover tooltip in a checkbox list. 

![bild](https://user-images.githubusercontent.com/15555035/62733455-2ee02880-ba16-11e9-8cf2-773e084b4387.png)

Is HTML queries and modifications after rendering only way, or is there a cleaner way I can achieve this?

**Comment by amsik** [comment]
Hi. https://amsik.github.io/liquor-tree/#Custom-Node

**Comment by undergroundwires** [comment]
Works smoothly, sorry for missing that in docs and big thank you for pointing out!
