### ISSUE TITLE
Put checkboxes on multiple nodes using IDs array

### ISSUE THREAD

**Issue by funkindy** [amsik/liquor-tree#148]
First of all thank you for the amazing library.

My goal is to put checkboxes on a bunch of nodes using an array of those nodes ids. For now i am doing it in a loop for each node like this:

```
ids.forEach((id) => {
    this.$refs.tree.find({id: id}).check()
})
```
This is very slow. 200 ids is being checked for about 10-20 seconds.

`selection.check()` for this amount of ids is way faster, but for now i didnt find out how to get selection with array of ids. It could look as easy as `this.$refs.tree.find({id: ids}).check()` where `ids `is array.

Maybe i am missing something because looks like a common pattern? Thank you.

**Comment by funkindy** [comment]
Just get x12 speedup with this workaround (the whole tree has about 3000 nodes):

```
ids.forEach((id) => {
    this.$refs.tree.tree.getNodeById(id).check()
})
```
But using internal methods really doesnt look good.

Maybe it would be a useful feature to add an array option to 'id' into `find `method?

**Comment by amsik** [comment]
Hi! Can you try:

```javascript
const nodes = this.$refs.tree.findAll(node => {
  return ids.includes(node.id)
})

nodes.check()
```

And could you please show a real example on https://codesandbox.io or similar?

**Comment by funkindy** [comment]
Thats great, this is by far the fastest way, many thanks. https://jsfiddle.net/ayLzop1v/25/
