### ISSUE TITLE
Drag and drop bug

### ISSUE THREAD

**Issue by Rosco89** [amsik/liquor-tree#149]
Hello @amsik !
I'm using this awesome package, but I have an issue.

Currently I'm returning false at onDragFinish() for testing purposes.

![Screenshot from 2019-09-05 08-41-28](https://user-images.githubusercontent.com/22955692/64317828-0158b180-cfb9-11e9-9684-884d648c6860.png)

When I drop the target node stays at the same depth, but always gets extra padding.

![Screenshot from 2019-09-05 08-43-44](https://user-images.githubusercontent.com/22955692/64318053-7d52f980-cfb9-11e9-89eb-dd0542407701.png)

In this picture you can see what is happening.

![Screenshot from 2019-09-05 08-40-32](https://user-images.githubusercontent.com/22955692/64317759-dc643e80-cfb8-11e9-87f9-bc2d98e2c33f.png)

How can I solve it the easiest way?

Thanks for your help!

**Comment by amsik** [comment]
Hi. Sorry... I did'n have time. Fixed in the next version (0.2.63)

**Comment by Rosco89** [comment]
Great! Thank you! Issue solved.
