### ISSUE TITLE
data reactivity

### ISSUE THREAD

**Issue by elguja** [amsik/liquor-tree#17]
Hello

I have problem to show some reactive data with node.data source.

Tried this workaround [https://github.com/amsik/liquor-tree/issues/9](url) but it does not work.
I want to pass data object through the computed getters but without results.

Please could you give me some clue how solve this problem.
Thank you in advance.

**Comment by amsik** [comment]
Hi!

It may help you: https://jsfiddle.net/amsik/j96d1v7e/
If not please give me more details.

**Comment by elguja** [comment]
Hi amsik
Thank you for quick reply

I am recieving large json object in live mode, via the axios from server and set it in vuex state.
Each entry of this object contains several values that I want to set in node.data and show as live indicators in node interface desing.
I tried to pass vuex getters of this object to the tree data, through the computed method, but it does not work.

As I understud from the link, I have to find all nodes first, and then set node.data via setInterval, yes?

Is there any other way to reactively show some live tada in the node?

**Comment by amsik** [comment]
Could you please provide some example on http://jsfiddle.net. You can skip a request to server :)

**Comment by elguja** [comment]
Here is an exmaple.
https://jsfiddle.net/elguja/a9fgxb35/

"dataFromServer" comes from server every several seconds and I want to show these values in node view.

//import { mapGetters } from 'vuex'
and
//computed: {
//  ...mapGetters(['dataFromServer']),
//}
are for reference only.

**Comment by amsik** [comment]
It is not realized... I saw a few ways when I started working on it:
- use reactive props to handle tree nodes
- override received data to understandable tree format 

I've chosen the 2th one. And there were reasons for this. I will investigate this issue soon. 

Anyway try out the Tree API, it might help:

https://amsik.github.io/liquor-tree/#Tree-API

**Comment by amsik** [comment]
I will add examples to the docs.  But you can try it yourself:

```shell
$ npm run dev
```

There will be **Vuex Integration** page

**Comment by amsik** [comment]
https://amsik.github.io/liquor-tree/#Integration-with-Vuex

**Comment by Xirui** [comment]
@amsik thanks for making this good component. I am kind of facing similar issue with data reactivity. Could you put a full example using vuex? Or show me an example of re-drawing the whole tree.

**Comment by amsik** [comment]
https://jsfiddle.net/amsik/163ryptv/

**Comment by elguja** [comment]
Hello amsik
It's nice to see development progress of your component and this is it what I wanted. Thank you for that!
But while it works fine in jsfiddle  (https://jsfiddle.net/elguja/9t8772dm/  - this code is only about to mount tree data), I could not make it work in vue-cli. 
I can see tree data in console log from action, mutation and even in mounted method, making initTree action return promise but it does not show the tree in my custom component.

treeOptions: {
        store: {
             store: this.$store,  
             key: 'tree',
             mutations: ['initTree']
        },
}
Is this correct way to pass this.$store in options' object?

**Comment by amsik** [comment]
I have checked. Your store object is using `modules`. Change your store initialization to code:

```javascript
export default new Vuex.Store(objectLoader);
```

I did not take this into account to my realization. I will do it as soon as possible.

**Comment by elguja** [comment]
Hello amsik

Is there some progress about implementing the component with store modules?

**Comment by amsik** [comment]
Hey! I had a vacation. I'll do it by the end of the day :)

**Comment by amsik** [comment]
Hi!

Here are some examples:

**Without modules**

```javascript
const Store = new Vuex.Store({
  state: {
    tree: []
  },
  mutations: {
    initTree(state, treeData) {
      state.tree.push(...treeData)
    },
    updateTree(state, newData) {
      state.tree = newData
    }
  },
  actions: {
    initTree(store) {
          return fetch('data.json')
            .then(r => r.json())
            .then(data => store.commit('initTree', data))
        }
  }
})

// components options
const opts = {
  store: {
    store: Store,
    key: 'tree',
    mutations: ['initTree', 'updateTree']
  },
  checkbox: true
}
```

**With modules**

```javascript

const TreeStore = {
  state: {
    tree: []
  },
  mutations: {
    initTree(state, treeData) {
      state.tree.push(...treeData)
    },
    updateTree(state, newData) {
      state.tree = newData
    }
  },
  getters: {
    tree(state) {
      return state.tree
    }
  },
  actions: {
    initTree(store) {
          return fetch('data.json')
            .then(r => r.json())
            .then(data => store.commit('initTree', data))
        }
  }
}

const Store = new Vuex.Store({
  treeModule: TreeStore
})

// components options
const opts = {
  store: {
    store: Store,
    getter: 'tree',  // change `key` to `getter`
    mutations: ['initTree', 'updateTree']
  },
  checkbox: true
}
```

**Comment by elguja** [comment]
Hello amsik!
About store modules everything is fine. Thank you for that.

But there is another problem. 
It can not keep the state (checked, expanded and so on). after a few time, when data comes from server, tree state is reseting...

**Comment by amsik** [comment]
Can you show me the response from the server?

**Comment by elguja** [comment]
**This is response object and I'm transforming it to format that component uses.**
[
        {
          groupName: "Group 1",
          objects: [
            {
              id: 1,
              objectCustomName: "Object 1",
              lastConn: { time: "2018-04-25T15:54:05.63", status: "Green" },
              lastPositionLive: { time: "2018-04-24T19:01:44", status: "Red" },
              position: { latitude: 41.707245, longitude: 44.8426317, z: 0 },
              cellularSignal: 32,
              isSatellite: false,
              accuracy: 112,
              speed: 0,
              movingStatus: false,
              engineStarted: null
            },
           ... (Other objects)
         ]
        },
 ... (Other groups)
 ]

**This is options object:**

treeOptions: {
               store: {
                    store: this.$store,
                    getter: 'objectBundle',
                    mutations: ['INIT_OBJECT_TREE', 'UPDATE_OBJECT_TREE']
                },
                checkbox: true,
                paddingLeft: 0,
                filter: {
                    emptyText: 'nothing found!'
    }
}

**Comment by amsik** [comment]
Please use Vuex for this.
