### ISSUE TITLE
toJSON() returns an empty array

### ISSUE THREAD

**Issue by I-Vargas** [amsik/liquor-tree#176]
Since version 0.2.65 (maybe 0.2.64, since it wasn't available I didn't test it) that there's been a bug in the toJSON method.

After setting the model of the tree if you call the toJSON method it returns an empty array instead of the tree.

I've created a fiddle that shows that, you can switch between version 0.2.63 and a more recent to see the regression, I'm printing it to the console.

Here's the fiddle: https://jsfiddle.net/9aup14h7/

P.S- I think a little more documentation would do some good, I saw the toJSON and the setModel methods reading issues and printing a tree to the console, they weren't mention on the documentation.

P.P.S- As well as GitHub releases and release notes. The last release on GitHub was on 2018-10-07, over a year ago. And of course the accompanying release note. For example noting how Selection was changed from returning null to returning an empty array if nothing was found.

**Comment by amsik** [comment]
Hi. I think it's VueJS specific issue. Because `data` property is changing by link. You have to add an empty object. 

```vue
<tree ref="tree" data="{}" />
```

**Comment by I-Vargas** [comment]
adding the data property with {} on the jsfiddle on version 0.2.67 didn't work, it's still not returning the tree model, it's now returning:

```
[{
    "data": {},
    "state": {
      "selected": false,
      "selectable": true,
      "checked": false,
      "expanded": false,
      "disabled": false,
      "visible": true,
      "indeterminate": false,
      "matched": false,
      "editable": true,
      "dragging": false,
      "draggable": true,
      "dropable": true
    },
    "children": []
  }]
```

That's not the model of the tree that's being displayed.

**Comment by amsik** [comment]
Ohh. Sorry... I forgot. I added a "hook" to increase the speed for rendering big tree. `setModel` method is working asynchrony now.

https://github.com/amsik/liquor-tree/blob/master/src/lib/Tree.js#L242

**Comment by I-Vargas** [comment]
That's a big change that should be included in a changelog or release notes. I didn't realize that it was asynchronous now.

The setModel isn't returning a promise thought shouldn't it be returning a promise for it to truly be a asynchronous? I've been using the async/await syntax, I tried awaiting the setModel, putting it inside of a Promise but it didn't work.

Could you do a fiddle with a working example? Thanks.

**Comment by amsik** [comment]
I've added it in the v0.2.68. Also here is an example: https://jsfiddle.net/amsik/fe63a28s/

**Comment by I-Vargas** [comment]
I think everything is working now, I was having a few problems with testing, but I solved it after seeing what you did with adding the setupTests.js file for the requestAnimationFrame.
