### ISSUE TITLE
injection __ob__ not found

### ISSUE THREAD

**Issue by 191082219** [amsik/liquor-tree#177]
When I'm using this component like this:
`import LiquorTree from 'liquor-tree';`

and 
`export default{
  ...
  components:{LiquorTree}
}`

most features are available 
but after the nodes being loaded
`injection __ob__ not found`  
appears  and features like example
`<span slot-scope='{node}'></span>`
is not worked and the node is undefined?

the version of  vue.js is 2.4.3.

**Comment by amsik** [comment]
Can you show me a read exaple? 

You can use https://codesandbox.io/ for it

**Comment by 191082219** [comment]
@amsik I'm so sorry that I forgot this issue because I fixed it.  It's a problem about the version of Vue. It seems that there is going to be sth wrong under the version 2.4.3.
