### ISSUE TITLE
Tree.find does not return text value that includes a bracket symbol

### ISSUE THREAD

**Issue by kayakinwunmi** [amsik/liquor-tree#18]
A weird bug I found is when a Node text value has brackets Tree.find returns false. 

`let tree = item.find({
          text: 'London (SE5)'
          id: 5,
          state: { checked: true }
        });
        if (tree) {
          tree.uncheck();
        }`

This returns null, however if I changed text to 'London - SE5' it works.

Also, does the Tree.find API search in data object?

Thanks

**Comment by amsik** [comment]
Hi! Thanks for using the library! I've fixed the issue. You can update from npm. 
Possible ways to use `find` method:

```javascript
const tree = this.$refs.tree

tree.find('London (SE5)')
tree.find({ text: 'London (SE5)', state: { checked: true } })
tree.find(/London/)
tree.find({
  data: {
    city: "London"
  }
})


```

**Comment by kayakinwunmi** [comment]
Thanks Amsik! I will get latest. 

Great work on the Vuex integration also!
