### ISSUE TITLE
Is to possible for only parent to call a function?

### ISSUE THREAD

**Issue by nemanja-ivanis** [amsik/liquor-tree#180]
I have a function binded on @node:checked  and @node:unchecked which calls an API endpoint and returns data. My problem is that each time a parent node is checked/unchecked the endpoint is called for each node/child inside that parent. Is there a way for a parent to call only once disregarding the children? I get all selected/unselected nodes before calling the endpoint so i just need to call it once on parent.

**Comment by amsik** [comment]
Hi! I've added a new version. 2th arguments was added when autoCheckChildren is true. You can try:

```javascript
this.$refs.tree.$on('node:checked', (currentNode, targetNode) => {
 if (!targetNode) {
  // ... call the API
 }
})
```

**Comment by nemanja-ivanis** [comment]
@amsik It works perfectly! Thanks!
