### ISSUE TITLE
Running liquor-tree

### ISSUE THREAD

**Issue by I-Vargas** [amsik/liquor-tree#181]
I cloned the repository and was trying to run it following the `README.md` instructions but it didn't work.

I also noticed that out of the 23 dependencies 20 were outdated with 17 of those were by outdated by a major version or more. There were a lot of deprecated warnings and vulnerabilities including high danger. And `@vue/test-utils` should be updated from `1.0.0-beta.25` to `1.0.0-beta.30` it includes major breaking changes on the way asynchronous code works. And I'm having trouble testing components that involve liquor-tree.

It also warned me that the `package.json` didn't contain a licence field.

I was gonna add a role="treeitem" to the node template.

With a cleanly cloned project not building before changing anything then I'm not inclined to actually contribute to it, I'm not gonna do a pull request with a broken build.

**Comment by amsik** [comment]
Hi! Check the new version (0.2.69)

**Comment by I-Vargas** [comment]
It's still not working, after cloning and doing `npm install` when I run `npm run dev` this is the output:
```
rollup v0.66.6
bundles src/main.js → dist\liquor-tree.esm.js...
[!] Error: 'default' is not exported by node_modules\vue-runtime-helpers\dist\normalize-component.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src\components\TreeRoot.vue (80:9)
78:
79:   export default {
80:     name: 'Tree',
             ^
81:     components: {
82:       TreeNode,
Error: 'default' is not exported by node_modules\vue-runtime-helpers\dist\normalize-component.js
...
```

When I run `npm run build` this is the output:
```
src/main.js → dist/liquor-tree.esm.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src\components\TreeRoot.vue: (23:9)
[!] Error: 'default' is not exported by node_modules\vue-runtime-helpers\dist\normalize-component.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src\components\TreeRoot.vue (23:9)
21:             v-if="node && node.visible()"
22:
23:             :key="node.id"
             ^
24:             :node="node"
25:             :options="opts"
Error: 'default' is not exported by node_modules\vue-runtime-helpers\dist\normalize-component.js
```

Could you also had role="treeitem" to the TreeNodes? just like the Tree already has the role="tree".

**Comment by amsik** [comment]
Fixed. Problem was with "rollup-plugin-vue" package

**Comment by I-Vargas** [comment]
Yeah `rollup-plugin-vue` breaks stuff. Maybe move away from rollup and just do the package using [vue-cli-service](https://cli.vuejs.org/guide/cli-service.html).

With this I'm closing this issue, I've opened a PR with a few commits, please check them.
