### ISSUE TITLE
How to save tree?

### ISSUE THREAD

**Issue by tranchau1991** [amsik/liquor-tree#19]
How to get all data of tree after change add,edit,delete,checked node?

**Comment by amsik** [comment]
Hi!

You can use `toJSON` method:

```javascript
this.$refs.tree.toJSON()
```

To get more examples clone the repo and try:

```shell
$ npm run dev
```
Then open Exporting page.

**Comment by tranchau1991** [comment]
Hi! Thank support.
But, I have test and get lost data ?
Need click expanded:true all level of tree, it will have all data for toJson() 
else not click expanded true data just level can see.
How to get all data of tree?

**Comment by amsik** [comment]
Could you show me an example? You can use https://codesandbox.io/ for it

**Comment by tranchau1991** [comment]
Sorry, current i need more time make demo in codesandbox,
I just make demo it http://jsfiddle.net/e0h2yvxp/4/

**Comment by amsik** [comment]
Check the console. By clicking the button it is showing the correct data
