### ISSUE TITLE
Example of find in documentation isnt correct

### ISSUE THREAD

**Issue by AlexSmirnov9107** [amsik/liquor-tree#2]
I found a small mismatch in example in documentation
you have 
`this.$refs.tree.find('Node Text') // It will find Node that has text 'Node Text'
this.$refs.tree.find(/Node Text/) // Using RegExp. It will find: Node Text ATAT, ATATA Node Text and so on...
this.$refs.tree.find({
  text: /^Item 2/,
  state: { checked: true, selected: true }
})`

when you find, it should be  stateS instead of state

**Comment by amsik** [comment]
We are passing the 'state' for a new Node. But should use 'states' for searching... I think it is not good.

Added possibility to use both: `state` or `states`
