### ISSUE TITLE
accessing the $store

### ISSUE THREAD

**Issue by ukjeep4x4** [amsik/liquor-tree#22]
i see you can pass in a variable to the options called store where you can access the store to get values(using in fetch data), but i'm getting some weird errors.

Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at a (liquor-tree.esm.js?6487:6)
    at VueComponent.connectStore (liquor-tree.esm.js?6487:6)
    at eval (liquor-tree.esm.js?6487:6)
  
how i'm calling it/configuration:

<tree v-if="websiteId != 0" :options="treeOptions" @node:selected="onNodeSelected" />

treeOptions: {
        store: this.$store,
        fetchData (node) {
          return HTTP.get(`/api/websitenavigation?nodeid=${node.id}&websiteId=${this.store.getters.websiteId}`).then(function (response) { return response.data })
        }
      }

if i take out the  store: this.$store and hard code the id (${this.store.getters.websiteId}, i get exactly as i would expect it to work.  any ideas or help?

thanks,
matt

**Comment by ukjeep4x4** [comment]
maybe a better question is how can i access a variable on the page or in the store from the fetchdata function?

**Comment by amsik** [comment]
Probably your case isn't connected to the library. Could you try this code:

```javascript
treeOptions: {
  store: this.$store,
  fetchData: (node) => {
    return HTTP.get(`/api/websitenavigation?nodeid=${node.id}&websiteId=${this.store.getters.websiteId}`)
    .then(function (response) { return response.data })
    .catch(function (err) { console.log(err); })
  }
}
```

**Comment by ukjeep4x4** [comment]
Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at a (webpack-internal:///./node_modules/liquor-tree/dist/liquor-tree.esm.js:6)
    at VueComponent.connectStore (webpack-internal:///./node_modules/liquor-tree/dist/liquor-tree.esm.js:6)
    at eval (webpack-internal:///./node_modules/liquor-tree/dist/liquor-tree.esm.js:6)

**Comment by ukjeep4x4** [comment]
more detail:

Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at a (liquor-tree.esm.js?6487:6)
    at VueComponent.connectStore (liquor-tree.esm.js?6487:6)
    at eval (liquor-tree.esm.js?6487:6)


a | @ | liquor-tree.esm.js?6487:6
-- | -- | --
  | connectStore | @ | liquor-tree.esm.js?6487:6
  | (anonymous) | @ | liquor-tree.esm.js?6487:6
  | Promise.then (async) |   |  
  | mounted | @ | liquor-tree.esm.js?6487:6
  | callHook | @ | vue.esm.js?efeb:2921
  | insert | @ | vue.esm.js?efeb:4158
  | invokeInsertHook | @ | vue.esm.js?efeb:5960
  | patch | @ | vue.esm.js?efeb:6179
  | Vue._update | @ | vue.esm.js?efeb:2670
  | updateComponent | @ | vue.esm.js?efeb:2788
  | get | @ | vue.esm.js?efeb:3142
  | run | @ | vue.esm.js?efeb:3219
  | flushSchedulerQueue | @ | vue.esm.js?efeb:2981
  | (anonymous) | @ | vue.esm.js?efeb:1837
  | flushCallbacks | @ | vue.esm.js?efeb:1758
  | Promise.then (async) |   |  
  | microTimerFunc | @ | vue.esm.js?efeb:1806
  | nextTick | @ | vue.esm.js?efeb:1850
  | queueWatcher | @ | vue.esm.js?efeb:3068
  | update | @ | vue.esm.js?efeb:3209
  | notify | @ | vue.esm.js?efeb:697
  | reactiveSetter | @ | vue.esm.js?efeb:1014
  | SET_WEBSITE | @ | store.js?61f4:203
  | wrappedMutationHandler | @ | vuex.esm.js?358c:697
  | commitIterator | @ | vuex.esm.js?358c:389
  | (anonymous) | @ | vuex.esm.js?358c:388
  | _withCommit | @ | vuex.esm.js?358c:495
  | commit | @ | vuex.esm.js?358c:387
  | boundCommit | @ | vuex.esm.js?358c:335
  | (anonymous) | @ | store.js?61f4:52
  | Promise.then (async) |   |  
  | getWebsite | @ | store.js?61f4:50
  | wrappedActionHandler | @ | vuex.esm.js?358c:704
  | dispatch | @ | vuex.esm.js?358c:426
  | boundDispatch | @ | vuex.esm.js?358c:332
  | set | @ | WebsiteSelect.vue?e89a:28
  | change | @ | WebsiteSelect.vue?4742:29
  | invoker | @ | vue.esm.js?efeb:2027
  | fn._withTask.fn._withTask | @ | vue.esm.js?efeb:1826
  | ListPicker._handleMouseUp

**Comment by ukjeep4x4** [comment]
![image](https://user-images.githubusercontent.com/29954486/41102621-53115850-6a35-11e8-80ca-d516559abe26.png)

**Comment by ukjeep4x4** [comment]
![image](https://user-images.githubusercontent.com/29954486/41102672-65e1674a-6a35-11e8-8d7b-3db621f662d7.png)

**Comment by amsik** [comment]
Oh, you have wrong `options` object. Check this page:

https://amsik.github.io/liquor-tree/#Integration-with-Vuex
