### ISSUE TITLE
drag and drop?

### ISSUE THREAD

**Issue by ukjeep4x4** [amsik/liquor-tree#24]
any plans to support drag and drop in the tree?  it's a great control, thanks for the hard work.

**Comment by nbnotabene** [comment]
Inspiration?: 
- http://angular-ui-tree.github.io/angular-ui-tree
- https://github.com/phphe/vue-draggable-nested-tree
  (demo: https://codepen.io/phphe/pen/KRapQm)

**Comment by amsik** [comment]
Yeh, I have plans about drag&drop. I will do as soon as possible.

**Comment by amsik** [comment]
Similar in #11
