### ISSUE TITLE
On open and close events

### ISSUE THREAD

**Issue by lucasumberto** [amsik/liquor-tree#25]
Hi!

I need to attach events listeners to the nodes when they are created (on open/expand) and when they are closed (on close/colapse) i need to map wich event was dismissed to re-attach it when open the node again.

Or some init node function that i can pre-define some code every time a node is opened.

There are any way to do it already that i am missing?

Thanks, i loved the plugin!

**Comment by amsik** [comment]
Hi! Thanks for using this plugin!

There are all possible events:
https://amsik.github.io/liquor-tree/#Events

Also you can use `node.data` property to store your data and check whenever you want to do something :) Or provide me some example and I will help you if you will have questions

**Comment by lucasumberto** [comment]
Thanks for the fast reply,

Actually i need help, but my code is too complex to make a example of the problem.
i will try to explain what i am doing:

I have a task manager, and when i'm in the process to create a task these task shows me a tree of all the chain of tasks that the one selected will create, lets call it sub-tasks (see image), and checkboxes to set which one will be created or not.

But for each sub-tasks created i need a tooltip on it (using bootstrap 3 tooltip). Theses tooltips are created dynamically because they need to show info about the sub-tasks and it cames via API that i insert these data into node.data

THE PROBLEM:
The tooltip is generated after i do:
this.tree.expandAll();
So i have all the nodes in the DOM and i can easily find they with jQuery and attach the tooltip event on it.
But when i close one node it is removed from the DOM and lose my tooltip event. When i open it again i want to attach the event again, i already had the structure prepared to do this (array with nodes ids to compare if it has tooltip) i just need an event dispatched by the node when it opens so i can: 

- get the node id, compare it in the list;
- create the tip with the infos for that sub-task;
- attach the tip event on the node;

And a event on close the node to:
- get the node id, and remove it from the list;

![tasks](https://user-images.githubusercontent.com/7528675/41668684-4394ed32-7486-11e8-9537-fd1629acd355.png)


Sorry about my english if something is hard to comprehend please tell me

**Comment by amsik** [comment]
If I understand you... you can try:

```javascript

this.$refs.tree.on('node:expanded', (node) => {
  if (!node.data.isTooltipAttached) {
    // attach tooltip
   node.data.isTooltipAttached = true
  }
})

```

**Comment by lucasumberto** [comment]
Thanks!
I wasn't able to listen the events the way you show, but i did got this way:

`<tree ref="tree" :data="treeData" :options="treeOptions" v-on:node:collapsed="closeNode($event)" v-on:node:expanded="openNode($event)"></tree>`

And isTooltipAttached saved some code lines.

The events docs section aren't much clear on how to use each of it.
Thanks for the insights!
