### ISSUE TITLE
refresh the node after event

### ISSUE THREAD

**Issue by rafmaghari** [amsik/liquor-tree#28]
how to reload the node after events ?

**Comment by amsik** [comment]
Hi! Could you give me more details or example?

**Comment by rafmaghari** [comment]
Hmm I want to refresh the nodes after I add an item

**Comment by rafmaghari** [comment]
Is there an event to reload the tree view sorry I am not in the house I can
send thd code

**Comment by rafmaghari** [comment]
For example I want to reload all the items in tree view after I save an item

**Comment by amsik** [comment]
Please take a look at the documentation: https://amsik.github.io/liquor-tree/#Tree-API. It should help you

**Comment by minedun6** [comment]
This feature exists in jsTree where you can ask the plugin to re-query the provided data source, either local array or backend. Let's say that someone changed the tree structure and you maybe you want to manually refresh the data coming from the backend.

**Comment by amsik** [comment]
You are able to refresh data via `setModel` method. Received data will override the data

**Comment by minedun6** [comment]
Perfect !
Maybe there could also be a way to change the data (attributes) coming from the backend but keep the state (selected/opened/checked) for each one.

**Comment by amsik** [comment]
Yeah, we have it. https://amsik.github.io/liquor-tree/#Redefine-Structure
