### ISSUE TITLE
How to get data with state from tree?

### ISSUE THREAD

**Issue by amehlen** [amsik/liquor-tree#29]
Hello,
is there a possibility to save the changed state in a json from the tree?
For example I have a predefined tree with no checked node. How can I get the data json with the checked nodes?
Best Regards

**Comment by amsik** [comment]
Hello, I hope it will help you: https://github.com/amsik/liquor-tree/issues/19.
If not please let me know.

**Comment by amehlen** [comment]
Thanks, the function `toJSON` gives me the data I want.
Is there a function to filter the state? In my project I only need the state "checked" and "indeterminate".

**Comment by amehlen** [comment]
I wrote a function for `JSON.stringify` to extract the needed states.
` var replace = function(key, value) {
        switch (key) {
          case "selected":
          case "selectable":
          case "expanded":
          case "disabled":
          case "visible":
          case "matched":
          case "editable":
          case "data":
            return undefined;
            break;
          case "children":
            if (value.length > 0) {
              return value;
            } else {
              return undefined;
            }
            break;
          default:
            return value;
        }
      };
var treeModel = JSON.stringify(this.$refs.tree.toJSON(), replace);`

This works fine to get a JSON String with the needed information.

Other question:
Which data can be stored in the data object in the data property of a tree node? Is it possible to put other information which are not relevant to the tree node expected data?

**Comment by amsik** [comment]
The property `data` is a single object on `node`. You can put any data to this object :)

**Comment by amehlen** [comment]
Thanks for your help :-) 👍
