### ISSUE TITLE
Must have

### ISSUE THREAD

**Issue by stanislav-web** [amsik/liquor-tree#3]
Hi, Comrade!
We're watching you and already noticed that our young Padawan getting basics of Open Source stack.
And of course we would like to see the high reliability of your work!
Unfortunately, at the moment we can not treat the source code - as a standard.
So we would like to see the implementation of testing and some of CI procedures ;-)

**Comment by amsik** [comment]
Hi, Macha! 
I will be happy to do this soon! Keep track of the task status :-)
