### ISSUE TITLE
vuex state not reading the "state" property of node?

### ISSUE THREAD

**Issue by ukjeep4x4** [amsik/liquor-tree#30]
i'm passing a state object to the tree via vuex(with a specific node selected), but it doesn't respect that i'm passing it in as selected?

**Comment by amsik** [comment]
Please give me more details or example.

**Comment by ukjeep4x4** [comment]
i'm trying to auto select the first node in the tree when binding via vuex.  so i'm setting the state variable selected to true, but the tree ignores it when binding the object?
