### ISSUE TITLE
Store & propertyNames

### ISSUE THREAD

**Issue by xGenovax** [amsik/liquor-tree#31]
Hellow !

I'm trying to use your nice component on a project, unfortunatly I just encountered several problems :(

So, the component beeing unable to update using computed props on :data, I noticed u added the new store option which I'm trying to use.

- Firstly I noticed that changing the propertyNames.children and propertyNames.id weren't working anymore (but text still works).
- Secondly I'm still unable to use Store's module

My tree options
`treeOptions: {
        store: {
          store: this.$store,
          getter: "treeStore",
          mutations: ["updateTree"]
        },
        checkbox: true,
        propertyNames: {
          text: "myname",
          children: "mychildren"
        },
        filter: {
          plainList: true
        }
      }`

My Store:
`import forest from "./forest"
const store = new Vuex.Store({
  modules: {
    forest
  },
});`
My Store module "forest"
`export default {
  namespaced: true,
  treeStore: [],
  getters,
  mutations: {
    updateTree(state, newData) {
      state.treeStore = newData;
    }
  },
  actions
};`

Could you give me a hand in order to solve those problems please?
Thank you kindly :p.

**Comment by amsik** [comment]
Hi! Thanks for using the library! 
It is not possible to use Vuex with `modules` now. Try without it. I will do it as soon as possible.

**Comment by xGenovax** [comment]
Thank you for your answer :).
And about the propertyname parameters, is it a bug ?

**Comment by Splinterjke** [comment]
Приветствую, Константин. Есть ли какие-то продвижения по поводу vuex? Mutations не отрабатывают.  Данные для геттера лежат в одном из модулей, с ним все ок, но в таком случае после любой выбранной ноды перестает работать expand/collapse в дереве в целом, классы для hover и selected.
Либа шикарна, уходить с нее не хочется, но стор душит.

**Comment by amsik** [comment]
Изменил поведение библиотеки с Vuex. Еще докумнтацию не обновил, пока не возможности это сделать. Но в [примерах](https://github.com/amsik/liquor-tree/blob/master/demo/pages/vuex.html) надеюсь все очень понятно сделано. Надеюсь поможет :) Пишите, если что-то не будет получаться или появятся какие-либо вопросы

**Comment by Splinterjke** [comment]
Однако, если геттер возвращает у объекта поле, представляющее массив для дерева, то сталкиваюсь с тем, что у выбранной ноды изменяется state, но expand/collapse перестает работать, как и классы для hover и selected.

**Comment by amsik** [comment]
Сделал решение в лоб, т.е. без всякой магии. На любой чих - нужно диспатчить экшн хранилища и это уже на плечах разработчика. 

Vuex не разрешает определять нескольно геттеров одним именем (даже в модулях), поэтому возможно и есть смысл сделать как и `mapGetters`, но вдруг будет другой кейс. где нужно будет сделать что-то эдакое :)

Долго думал о решении, но как по мне, данный подход решает любой кейс:
- Что-то сделал с хранилищем - проверели, не изменилось ли дерево (это еще не реализовано, всмысле проверка) - отрисовали.
- Что-то сделали с деревом (пользователь), выделили, удалили - вызываем диспатчер, который уже решит что с **новым** состоянием делать.

Этот подход может быть использован и для других `store`, нужно только реализовать `subscribe` и будет все так же работать, как и с Vuex. Пока таких кейсов не приходило :)

**Comment by amsik** [comment]
Делал не мало тестов, и единственное что нашел - так это потеря фокуса дерева. Этим займусь, как освобожусь чуток. Можно глянуть на Ваш пример (либо что-то близкое) ? Подумаю, что можно будет с этим сделать

**Comment by Splinterjke** [comment]
В модуле есть стейт:
`
state: {
    contract: null
  }
`
В одном из экшенов делаем запрос к api и мутируем стейт:
`
state.contract = payload.data;
`
В этом модуле для дерева указан геттер:
`
 getTreeData: state => {
     if (state.contract == null) return [];
     return state.contract.clause.clauseParts;
}
`
Внутри clauseParts могут быть другие коллекции clauseParts (вложенность n уровня)
treeOptions:
`
treeOptions: {
        propertyNames: {
          text: "name",
          children: "clauseParts"
        },
        store: {
              store: this.$store,
              getter() {
                return this.$store.getters.getTreeData
              },
              dispatcher(tree) {
                this.$store.dispatch('updateTree', tree)
              }
            }
        multiple: false
}
`
Есть много других экшенов, которые мутируют contract запросом к api.
Экшен updateTree также создан, пробовал вариант, где внутри этого экшена нет логики т.к. contract.clause.clauseParts обновляется с изменением contract в других экшенах. Пробовал вариант с логикой в updateTree, где в contract.clause.clauseParts записываю map от tree параметра т.к. tree в мутации имеет объект дерева, из которого мне нужно выдрать data из node, чтобы записать в contract.clause.clauseParts. Пробовал вариант с отдельным стейтом для дерева и его обновлением в мутации уже без map. Всегда получаю результат, что после первого выбора ноды мы не можем больше экспандить ноды и стили select/hover не применяются, но ноды все еще можно селектить.

**Comment by amsik** [comment]
А можно глянуть `updateTree`?

**Comment by amsik** [comment]
Любое изменение в строре - заставит обновить данные в дереве. Т.е. Прийдут с сервера, либо вызов api... В нашем случае вернет:
```javascript
getTreeData: state => { 
  if (state.contract == null) return []; 
  return state.contract.clause.clauseParts; 
}
```
Какая бы ни была сложная логика - что вернет этот геттер, то и увидем в дереве. Если что-то было выделенно, а дерево это не нарисовало - значит что-то вернулось не верное...

```javascript
contracts.mutations.updateTree = (state, tree) => {
  state.contract.clause.clauseParts = tree;
};
```
Этого должно быть достаточно... на крайний случай this.$set

**Comment by Splinterjke** [comment]
tree в параметре это объект дерева, а clauseParts это объект с бэка, в нем нет изначально statesб children, data. С помощью handleClauseParts я создаю data для clauseParts. Кстати, states у нод в объекте tree не изменяется, может поэтому ui select и expand не отрабатывают?

**Comment by amsik** [comment]
Изначально в `clauseParts` нет states, все верно. Но после первого кола `updateTree` - они появятся и буду работать. Если же конечно это св-во не обновляется с сервера постоянно. В это случае делать это лучше через `fetchData`, тогда и `clauseParts` обновится через мутации.
