### ISSUE TITLE
Passing reactive variables to the fetchData in treeOptions

### ISSUE THREAD

**Issue by Starvigil** [amsik/liquor-tree#33]
Hi, I'm trying to load the children of a selected node async via axios. Problem is that I need to pass some params and headers that are generated/ selected during the runtime. 
Using this.property only returns undefined, despite defining it in the data(). Using this.$store or this.$data doesn't work either. Only thing that works is defining a property above the export default in the script, but then that's not reactive either. 

treeOptions: {
        parentSelect: true,
        checkbox: true,
        fetchData(node) {
         console.log("fetchSession: ",  **this.session**)
          return axios.get(`/treedata/${node.id}`, {
            params: {
              **session: this.session**
            },
            headers: {
              "**body": this.body**,
            }
          }).then(response => {
            // JSON responses are automatically parsed.
            console.log("TreeDataResponse: ", response)
            let obj = response.data.Objects
            return Promise.resolve(obj)
          })
          .catch(e => {
            console.log("error: ", e)
          })

**Comment by amsik** [comment]
You probably don't have the link the an vue instance. 

```javascript
new Vue({
  el: '#app',
  data() { // do not use arrow function here
    const vueInstance = this

    return {
      fetchData() {
        return axios.get(`/treedata/${node.id}`, {
            params: {
              session: vueInstance.session
            },
            headers: {
              "body": vueInstance.body,
            }
          }
        }
      }
    }
  }
})

```

**Comment by Starvigil** [comment]
Thanks, I'll try that out. But I just found another solution that works. I can reference a method for fetchData. And there I can use everything.

``` 
data() {
    return {
      ...
      treeFilter: '',
      treeOptions: {
        parentSelect: true,
        checkbox: true,
        fetchData: this.getFetchData
      },
      }
  },
  methods: {
      getFetchData (node) {
        console.log("getFetchData: ", node.id, this.$store.getters.session)
        return axios.get(`/treedata/${node.id}`, {
        params: {
          session: this.$store.getters.session
        },
        headers: {
          "body": this.body,
        }
        }).then(response => {
        // JSON responses are automatically parsed.
        console.log("TreeDataResponse: ", response)
        let obj = response.data.Objects
        return Promise.resolve(obj)
        })
        .catch(e => {
        console.log("error: ", e)

        })
    },
```
