### ISSUE TITLE
prevent collapse when selecting a node with children

### ISSUE THREAD

**Issue by JasonHenson** [amsik/liquor-tree#34]
I would like to only collapse a node when clicking the expand/collapse icon -- not when selecting the item directly. Typically, I can do something like event.stopPropagation() or event.preventDefault() to accomplish this, but would need access to the actual click event being fired not the node itself. 

Any thoughts if this is possible now in some way I am not seeing or could support be added? Thank you.

**Comment by amsik** [comment]
https://amsik.github.io/liquor-tree/#Component-Options
You can use `parentSelect` option.

**Comment by JasonHenson** [comment]
Wow, super easy -- thank you!
