### ISSUE TITLE
Doesn't reflect the node state from store

### ISSUE THREAD

**Issue by liola** [amsik/liquor-tree#35]
When tree initialized with some state(for example "expanded": true) this state doen't get applied and tree goes with default behavior. 
Example [https://codesandbox.io/s/41y00nvw0](url) 
See root node state `expanded=true` but tree is not expanded. Try clicking `Test Reactivity` button.
![vuex_state](https://user-images.githubusercontent.com/32328613/43191094-25e99d26-9003-11e8-8eee-35962dd0902e.PNG)
![tree_state](https://user-images.githubusercontent.com/32328613/43191102-2acdd2f8-9003-11e8-84ea-4c438f3a5062.PNG)

**Comment by amsik** [comment]
See [docs](https://amsik.github.io/liquor-tree/#Integration-with-Vuex). Here is an example how to use Vuex.
