### ISSUE TITLE
can't access vuex modules

### ISSUE THREAD

**Issue by you06** [amsik/liquor-tree#39]
Hi,
I'm integrating this tool with Vuex, and have the following problem.
According to the [documents](https://amsik.github.io/liquor-tree/#Integration-with-Vuex), integrated with Vuex should pass **Vuex store object** into `treeOptions`

The file tree looks like this (see also [github repo](https://github.com/Airyworks/scarlet/tree/dev/src/renderer))

```
.
├── components
|   ├── common
|   |   └── Filetree.vue
|   |   └── ...
|   └── ...
├── store
|   ├── modules
|   |   ├── Filetree.js
|   |   └── ...
|   └── index.js
└── ...
```

When I create several modules, the states of each modules are separated but the mutations are mixed. It seems unable to get a Vuex store object.

In my understanding, this plugin will copy the reference of its data into Vuex state in `initTree` mutation. Can I pass only listened state property and some actions(or mutations) into `tree options`? So that I can visit the required objects from Vue file via `mapState`, `mapActions` and `mapMutations`.

**Comment by amsik** [comment]
Hi! It is not implemented yet. So you cannot use Vuex modules

**Comment by amsik** [comment]
Ohh, I'm sorry. You able to get the data from the modules... See the example:

Your store (from your example)
```javascript
export default new Vuex.Store({
  modules: {
      reading: {
          state: {}, // ....
          mutations: {},
          actions 
      },

      filetree: {
          state: {
              treeData: []
          },
          mutations = {
            initTree(state, treeData) {
                state.treeData.push(...treeData)
            },
            updateTree(state, newData) {
                state.treeData = newData
            }
          }
      }
  },

  getters: {
      tree(state) {
        return state.filetree.tree  // reads 'tree' state from `filetree` module
      }
  },

  strict: process.env.NODE_ENV !== 'production'
})
```

`liquor-tree` options:

```javascript
treeOptions: {
          paddingLeft: 10,
          store: {
            store: this.$store,
            getter: 'tree', // ~~~  use `getter` instead of `key`
            mutations: ['initTree', 'updateTree']
          }
        }
```

**Comment by you06** [comment]
@amsik thanks for your demo!
Set getter in `tree options` works, however, the mutations in vuex modules seems will not be executed.
I'm currently using `mapMutations` and [event trigger](https://amsik.github.io/liquor-tree/#Events) to execute mutation in vuex modules.

btw, a quotation mark is missing in [vuex document page](https://amsik.github.io/liquor-tree/#Integration-with-Vuex) line 21.
![image](https://user-images.githubusercontent.com/9587680/43643871-3bb9a3ae-975f-11e8-9820-946d06d965b0.png)

Cool tree display tool!
