### ISSUE TITLE
`data` prop not reactive ?

### ISSUE THREAD

**Issue by entr** [amsik/liquor-tree#4]
Hey, just tried liquor-tree and as it seems from initial tests it's not reactive. My data is primary asynchronous and all my components have no data when mounted and rely on the reactive nature of vuejs. I looked at liquor source and it looks like the render uses a model property that is generated only once on `mounted()` (once per component instance) and not part of `data()` function.

**Comment by entr** [comment]
Thanks for the quick response! I'll give it a try sometime later

**Comment by amsik** [comment]
Thanks for using the library! I try to add this functionality as soon as possible :)

**Comment by amsik** [comment]
Tree supports a certain data format. Sometimes it has to be converted. VueJS is not reccomend to `mutate props`. 

I've added supportion of asynchronous data. See [this](https://github.com/amsik/liquor-tree/commit/590f4b9cbdadeb489fccb354bd2525e95ae11eb8) commit

**Comment by entr** [comment]
@amsik thanks for looking into this.

While what you implemented will work it requires us to pass a specially crafted `fetchData()` method just for this and generally we have already handled the async part in vuex for example. Instead I imagined you can do something like this internally:

```js
export default {
  props: ['initialTreeData'],

  treeData() {
    return {
      data: this.initialTreeData,
    }
  },
  
  watch: {
    treeData( newData ) {
      this.treeData = newData
      // do data transformations etc
      // trigger UI refresh
    }
  }
}
```

which also doesn't mutate the prop. Hope that makes sense.

**Comment by entr** [comment]
Sorry, `watch: { treeData() {} }` should be `watch: { initialTreeData() {} }` in the example above.

**Comment by entr** [comment]
Well, I'll just repost the example. It must had been a really long week for me:
```js
export default {
  props: ['initialTreeData'],

  data() {
    return {
      treeData: this.initialTreeData,
    }
  },
  
  watch: {
    initialTreeData( newData ) {
      this.treeData = `newData`
      // do data transformations etc
      // trigger UI refresh
    }
  }
}
```
Sorry for the notification spam :)
