### ISSUE TITLE
question: integrate node state with vuex

### ISSUE THREAD

**Issue by you06** [amsik/liquor-tree#40]
I'm currently make a file browser with lazy load. The file tree data is stored in Vuex modules. I found using your demo in #39 will store file tree data and node text in Vuex. What I want is **store expanded state in Vuex** also, so that when I load new data into Vuex the nodes won't collapsed automatically.

Just copy the [demo](https://github.com/amsik/liquor-tree/blob/master/demo/pages/vuex.html) into [jsfiddle](https://jsfiddle.net/eydh4956/38/). Line 152 in HTML editor, set `t.state = { expanded: true }`, but the nodes will collapse (expected all nodes to be expanded).

So the question is can I store node state in Vuex?

Thanks!

**Comment by amsik** [comment]
Hi. You can try it from the repo. I will publish it later to the npm.

**Comment by you06** [comment]
Thank you @amsik , it works fine! Waiting for the npm publish.

**Comment by amsik** [comment]
Package is published on `npm`
