### ISSUE TITLE
Get parent node and all parent of that node

### ISSUE THREAD

**Issue by nicky508** [amsik/liquor-tree#47]
I implemented the Liqour tree and it works great. However I have one question, which I do not succeed with. Right now I have a tree structure with checkboxes. I use this line to get the results: 

`<pre style="display: none;" id="selectedFeaturesDiv" v-if="treeModel"> {{ treeModel.checked.map(el => el.parent.text + ";" +el.text) }} </pre>`

This gives me the checked nodes and the parent node. However I want to know all parents of the specific node not only the first, but also the parent of the parent until the root node. Is this possible?

**Comment by amsik** [comment]
Hi! Yeah, it is possible.

```javascript
  function getFullPath(node) {
    const fullPath = [node.text]
    node.recurseUp(parentEl => fullPath.unshift(parentEl.text))
    return fullPath.join('->')
  }
```

```html
<pre style="display: none;" id="selectedFeaturesDiv" v-if="treeModel"> 
 {{ treeModel.checked.map(el => {getFullPath(el) + ";" +el.text) }} 
</pre>
```

**Comment by nicky508** [comment]
Great! Thnx it works perfect!
