### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by abdohafez** [amsik/liquor-tree#49]
The tree is not being rendered on IE11, knowing that it's working perfectly on other browsers.

**Comment by amsik** [comment]
Hi! It is not possible to use the library on IE11 without poliffils. You have to add:

- for `Object.assign`
- for `Promise`

For example:

```html
<script src="https://cdn.jsdelivr.net/npm/object-assign-polyfill@0.1.0/index.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.js"></script>
```
It should help you

**Comment by abdohafez** [comment]
Hello, Thanks for the prompt response.

I already have the polyfills included. yet I'm getting this error:

<img width="1028" alt="screen shot 2018-09-20 at 13 03 43" src="https://user-images.githubusercontent.com/8437364/45814419-d278fb00-bcd5-11e8-9996-955a6c39f59d.png">

**Comment by amsik** [comment]
Could you show me the real code example? I'll try to help you

**Comment by abdohafez** [comment]
Here are the files: 

**Index.html**

`<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <title>Corporate Information Resources</title>
  
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.de,Intl.~locale.en"></script>
  <script src="https://cdn.jsdelivr.net/npm/object-assign-polyfill@0.1.0/index.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.js"></script>
</head>
<body>
  <noscript>
    JavaScript has to be enabled to view the contents of this page.
  </noscript>
  <div id="app"></div>
  
</body>
</html>
`

**Tree.vue**

`<template>
    <tree
      ref="tree"
      :data="data"
      :options="treeOptions"
      class="treeview"
    />
</template>
`

**Comment by abdohafez** [comment]
it turned out that babel-polyfill was causing all the issues. removing it as an entry in the webpack config solve it.

``module.exports = {
  entry: {
    main: [ 
      './ie-polyfill',
      // 'babel-polyfill', // the problematic and redundant polyfill
      'aurelia-bootstrapper'
    ]
  },``

**Comment by amsik** [comment]
Yeah, this is another way to solve the problem... Who needs IE11 support is able to solve the problem using 2 ways (maybe more, I don't know):

- polyfill 
- babel presets
