### ISSUE TITLE
I can not get selected node after append

### ISSUE THREAD

**Issue by andre-novapc** [amsik/liquor-tree#50]
Hi.

I am trying to get the node after appending it, but I'm not getting.

My code:

`
let node = this.$refs.tree.append({ text: 'My Text', state: { selected: true }});

let selection = this.$refs.tree.selected();

alert(selection.length);  // <-------- this always stays zero
`

Can you help me solve this?

Thank you in advance.

**Comment by amsik** [comment]
Hi!

Yeah, it is a bug. I will fix it soon.

To solve this problem now you can use:

```javascript
let selection = this.$refs.tree.find({ state: {selected: true}})
```

**Comment by andre-novapc** [comment]
This works! Thanks.

**Comment by amsik** [comment]
Now your code will works:

```javascript
let node = this.$refs.tree.append({ text: 'My Text', state: { selected: true }});
let selection = this.$refs.tree.selected();
```
