### ISSUE TITLE
Possibility to grab the path for node

### ISSUE THREAD

**Issue by minedun6** [amsik/liquor-tree#51]
Using the current API, is it possible to get the path to a given node ?
 Let's say I have this kind of structure.
 - Root Node
    - Child Node 1
       - Child Node 1.1
          - Child Node 1.1.1
             - Child Node 1.1.1.1
                - Child Node 1.1.1.1.1 -> "node in question"
       - Child Node 1.1
    - Child Node 2

How can I get the path to the "Child Node 1.1.1.1.1 [node in question]" ?

**Comment by amsik** [comment]
Hi! Yeah, you have few ways to do it.

1) https://github.com/amsik/liquor-tree/issues/47

2)
```javascript
const selected = this.$refs.tree.selected()[0] // it might be more than 1 node or u can use `find`
selected.recurseUp(parentNode => console.log(parentNode.text))
```

**Comment by minedun6** [comment]
Great !
We might need someone to document these hidden gems to be honest. It could save us/you the time to wait for the answer and you definitly reducing the number of issues related to bug/issues instead of people asking for the api.
