### ISSUE TITLE
Async load node children

### ISSUE THREAD

**Issue by minedun6** [amsik/liquor-tree#56]
Is it possible to asynchronously load node children when selecting/expending the target node.
I only want to show the children after expanding the parent and append them to the parent.

![image](https://user-images.githubusercontent.com/4510058/46737182-c5c34380-cc92-11e8-8ba0-c98d30f9d257.png)

Do you mind adding an example ?

Here's the component code if it helps

```vue
<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <span>
                                <i class="far fa-folder"></i>
                                Digital Assets
                            </span>
                            <div class="d-flex">
                                <input type="text" class="form-control form-control-sm mr-3" v-model="query">
                                <div class="dropdown">
                                    <a class="btn btn-secondary btn-sm dropdown-toggle" href="#" role="button"
                                       id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">

                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" href="#">
                                            Open All
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            Collapse All
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            Refresh
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <!-- load the tree here -->
                        <liquor-tree
                                ref="tree"
                                :options="treeOptions"
                                :filter="query"
                        >
                            <div class="tree-scope" slot-scope="{ node }">
                                <template v-if="!node.hasChildren()">
                                    <i :class="node.data.icon"></i>
                                    {{ node.text }}
                                </template>

                                <template v-else>
                                    <i :class="[node.expanded() ? 'far fa-folder-open' : 'far fa-folder']"></i>
                                    {{ node.text }}
                                </template>
                            </div>
                        </liquor-tree>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    import LiquorTree from 'liquor-tree'

    export default {
        name: 'assets-library',
        data: function () {
            return {
                treeOptions: {
                    selectedArrowOnly: true,
                    fetchData(node) {
                        return fetch(`/tree?id=${node.id}`)
                            .then(r => r.json())
                            .then(items => {

                                items.forEach(setData)

                                function setData(item) {
                                    item.data = item

                                    if (item.children) {
                                        item.children.forEach(setData)
                                    }
                                }

                                return items
                            })
                    },
                },
                query: ''
            }
        },
        methods: {},
        components: {
            LiquorTree
        }
    }
</script>

<style>
    .tree-node.matched > .tree-content {
        background: #f7f2e7;
    }
</style>
```

**Comment by amsik** [comment]
Hi! Try to clone this repo and run `npm run dev`. There are examples in the menu item **Async Loading.**

`fetchData` options is using only for nodes which has `isBatch` property. And it loads nodes by `expand` node. To simulate this action you need to call manually. For instance:

```javascript
 // this is a link to the API. maybe it would be nice to rename...
const treeAPI = this.$refs.tree.tree;

tree.$on('node:selected', node => {
   treeAPI.loadChildren(node).then(_ => {
      // child are loaded
   })
})
```

Also you no need to add children for children nodes:

```javascript
function setData(item) {
   item.data = item

   if (item.children) {
     item.children.forEach(setData)
   }
}
```
It will be done automatically.

**Comment by minedun6** [comment]
Much appreciated my friend.

Other questions that might need some answers, without creating another issue :
 
Is it possible to display a little loading spinner when loading the children ?
And is it possible to disable the nodes animation when you expand the parent ?
And is it possible to know which node is the root element of the tree ?
And lastly, is it possible to add the expand arrow, no matter what but remove/hide it if after calling the api and checking if it has children ?

**Comment by amsik** [comment]
1) I will create a new issue. I forgot about this.
2) Animation realized via `css transition`. You can easily remove it: 
```css
.tree-children {
  transition: unset;
}
```
3) You are able to add more than 1 node to the root. To check if the node is root you can: 
```javascript
  node.isRoot() && node.tree.model.length === 1
```

4) You can use `css`. I need more real example to understand :)

**Comment by minedun6** [comment]
Regarding the 3rd question :
I'm not asking if the given node is root or not, but I'd like if the "tree" can return its root element.
The point is I need the root element to be originally exapanded and to disable getting the children of the root node. That's why I'm asking about this.

Regarding the 4th question :
Right now, I'm triggering the load children function by selecting on the whole node, I want to be able to do that only on the expand icon.
Here's an example I'm taking from another tree library.
[Vue jsTree](https://zdy1988.github.io/vue-jstree/)

![image](https://user-images.githubusercontent.com/4510058/46823933-6b57df00-cd87-11e8-9780-73d834259b80.png)

Even though it still hasn't loaded the children, the icon is still visible, but when the parent for which you are trying to load its children doesn't have any children, the icon disappears.

**Comment by amsik** [comment]
I will add a new method for root element. I think it will be useful not only for you.

You have a few ways:

1) Use `fetchData` ONLY for nodes, which has an `isBatch` attribute. It calls only by expanding the node. Here you can use promise or what you want to load children. But it shows the arrow near the node. Conclusion: arrow shows only when node has `isBatch` === true or when it has child.

2) Add event listeners (node:selected, node:checked and so on). Here you can use a JavaScript API to get data from the server. After receiving the data just insert it to the node.

For example

```javascript
onNodeSelected(node) {
  axios.get('/user', {
    params: {
      ID: node.id
    }
  }).then(data => {
    node.append(data)
  })
}


```

**Comment by amsik** [comment]
New version is available. There are 2 changes:

- loading indicator
- `this.$refs.tree.getRootNode()` method. It will return list if there are more than 1 root node.

**Comment by minedun6** [comment]
You are the best my friend.
I'm sorry if I'm throwing so many questions but for me who is using jsTree (jQuery) and want to change to vue, there are some nice features that I would like to see in this package.

**Comment by amsik** [comment]
I've updated the [docs.](https://amsik.github.io/liquor-tree/#Async-Data) It might help you.

**Comment by rayxcl** [comment]
> Yeah. You can clone the repo and [play with the library](https://github.com/amsik/liquor-tree/#development). Also it is a simplest example:
> 
> ```
> <tree :options="treeOpts" :data="treeData" />
> ```
> 
> ```js
> data: () => ({
>  treeOpts: {
>    fetchData(node) {
>        return fetch(`/assets/data/fetch0/data-${node.id}.json`).then(r => r.json())
>    }
>  },
>  treeData: [
>    text: 'Root node',
>    id: 'root', 
>    isBatch: true   
>  ]
> })
> ```
> 
> File `/assets/data/fetch0/data-${node.id}.json`
> 
> ```json
> [
>   {
>     "text": "Getting Started",
>     "isBatch": true,
>     "id": 1
>   },
>   {
>     "text": "Patterns",
>     "isBatch": true,
>     "id": 2
>   },
>   {
>     "text": "Has an error",
>     "isBatch": true
>   }
> ]
> ```
> 
> Nodes which has `isBatch` property will be shown with arrows.



> Yeah. You can clone the repo and [play with the library](https://github.com/amsik/liquor-tree/#development). Also it is a simplest example:
> 
> ```
> <tree :options="treeOpts" :data="treeData" />
> ```
> 
> ```js
> data: () => ({
>  treeOpts: {
>    fetchData(node) {
>        return fetch(`/assets/data/fetch0/data-${node.id}.json`).then(r => r.json())
>    }
>  },
>  treeData: [
>    text: 'Root node',
>    id: 'root', 
>    isBatch: true   
>  ]
> })
> ```
> 
> File `/assets/data/fetch0/data-${node.id}.json`
> 
> ```json
> [
>   {
>     "text": "Getting Started",
>     "isBatch": true,
>     "id": 1
>   },
>   {
>     "text": "Patterns",
>     "isBatch": true,
>     "id": 2
>   },
>   {
>     "text": "Has an error",
>     "isBatch": true
>   }
> ]
> ```
> 
> Nodes which has `isBatch` property will be shown with arrows.

May I ask how to use "async data" and "vuex" together?
My codes like below, but not working properly. 
The value of getTreeData is not updated and no tree displayed. 
Could you help me?

```
<tree :options="treeOpts" :data="getTreeData" />
```

```
data: () => ({
 treeOpts: {
   fetchData() {
       return axios.get('/api/tree')
        .then((response) => {
          let treeData = response.data
          this.$store.dispatch('updateTree', treeData)
   }
 },
 computed: {
    ...mapGetters( [ 'getTreeData' ] )
 }
```

```
getters: {
  state: {
    treeData: []
  },
  getTreeData: function (state) {
      return state.treeData
   }
 },
  mutations: {
    updateTree (state, newTree) {
      state.treeData = newTree
    }
  },
  actions: {
    updateTree (context, tree) {
      context.commit('updateTree', tree)
    }
  }
```

**Comment by amsik** [comment]
```javascript
treeOpts: {
    fetchData() {
        return axios.get('/api/tree')
            .then((response) => {
                let treeData = response.data
                this.$store.dispatch('updateTree', treeData)
                return treeData
            }).catch(function(error) {})
    },
    store: {
        store: Store,
        getter: () => {
            return this.$store.getters.getTreeData
        },
        dispatcher(tree) {
            this.$store.dispatch('updateTree', tree)
        }
    }
}
```

Try this code. It should fix your problem
