### ISSUE TITLE
Possibility to override default search method

### ISSUE THREAD

**Issue by minedun6** [amsik/liquor-tree#59]
Q1 . Is it currently possible to override the default search method ?
I need to get the search results from an API instead of doing some client search ?

Q2. Is it possible to find an element by something else other that the text ?
I did the following 
```js
tree.find({ id : childNodeId }) // wrong result
```

but going this approach got me the right results
```js
tree.find( n => n.id === childnodeid ) // right result
```

**Comment by amsik** [comment]
> Q1 . Is it currently possible to override the default search method ?

You can pass a function to override the default behaviour.

> tree.find({ id : childNodeId }) // wrong result

It works for me. This method returns [Selection API](https://amsik.github.io/liquor-tree/#Selection-API).

**Comment by minedun6** [comment]
> > Q1 . Is it currently possible to override the default search method ?
> 
> You can pass a function to override the default behaviour.

What's the method to override ?

> > tree.find({ id : childNodeId }) // wrong result
> 
> It works for me. This method returns [Selection API](https://amsik.github.io/liquor-tree/#Selection-API).

Odd. I tried using it yesterday and it returned the rootNode instead of the first child node.

**Comment by amsik** [comment]
For example:

```javascript
const treeData = [
  {text: 'D15', data: {d: 15}},
  {text: 'D20', data: {d: 20}},
  {text: 'D25', data: {d: 25}},
]

const items = this.$refs.tree.findAll(node => node.data.d >= 20)
```

**Comment by minedun6** [comment]
> Q1 . Is it currently possible to override the default search method ?
> You can pass a function to override the default behaviour.

Still having figured out how to override the default search behavior.

I'd appreciate if you could do showcase/example how to.

This is the approach I tried
```js
treeOptions: {
     minFetchDelay: 500,
     dnd: true,
     filter: function (query) {
           console.log(query) // still does the same work
     },
```

**Comment by amsik** [comment]
Ohh. Search and filtering are slightly different. 

* To override filtering:

```javascript
filter: {
    matcher(query, node) {
        return query == node.data.complexity
    },
    showChildren: false
}
```

* To find node (and proceed to use it via API):

```javascript
const node = this.$refs.tree.find({text: /^text/})

const node = this.$refs.tree.find({state: disabled})

const node = this.$refs.tree.find(node => {
  return node.data.SOME_PROP === 55
})
```

You will find a lot of examples if you clone repo and `npm run dev`

**Comment by minedun6** [comment]
I already cloned the project, there's much I gotten out if it to be honest.
What I actually want to do is, instead of doing the search on the front, I want to send a request to the backend.

The snippets you posted are fine when filtering/searching on the front, but since I'm asynchronysly load the children, going down this approach won't help me.

**Comment by amsik** [comment]
I can help you if you show me what you want to do. Snippets below can solve almost any possible problem (I think...):

```javascript
fetchData(node) {
  // Here you do search on the server.
  return fetch(`/searchAPI?nodeID=${node.id}`).then(r => r.json())
 
 // you can send whatever you want
 return fetch(`/searchAPI?p=${node.data.p}&d=${node.data.d}`).then(r => r.json())
}
```

Also you can do search on client side. For example you have a huge array of data (`const users = []`).

```javascript
 fetchData(node) {
   return new Promise(resolve => {
     resolve(
       users.filter(user => node.data.roles.includes(user.role))
     )
   })
 }
```

Note that this method calls only if *node* has `isBatch` property.
