### ISSUE TITLE
Component option parentSelect to prevent the expand/collapse when clicking text and prevent select when clicking arrow icon

### ISSUE THREAD

**Issue by reymark-torres** [amsik/liquor-tree#6]
Is there an available solution to this?
Btw @amsik , your plugin is good and has a potential to grow. :)

Thank you.

Cheers,

Reymark

**Comment by amsik** [comment]
Hi! Thank you for your comment. I will try to do it better :)

I did not fully understand your problem. Could you please show me the problem on JSFiddle? You can use this *snippet*: https://jsfiddle.net/amsik/ff1vyuug/. Add some changes and press Update button. Then give me a link.

Thanks!

**Comment by reymark-torres** [comment]
Hi @amsik. Thank you for your quick response. :)

Based on your sample fiddle, I have two key points:
1. When I click the text "Item 2", it should not expand nor collapse its children.
2. The only way I could/should expand/collapse its children is by clicking the arrow keys

- Because when I click the text "Item 2", my only intention is to select the item not expanding/collapsing it

Hope you understand it much better. :)

Thanks,

Reymark

**Comment by amsik** [comment]
Please try it out: https://jsfiddle.net/amsik/ff1vyuug/6/.
I've just added the options `parentSelect: true`

**Comment by reymark-torres** [comment]
Alright looks pretty neat. Thanks! :)
