### ISSUE TITLE
Change tree-arrow place

### ISSUE THREAD

**Issue by marcosrocha85** [amsik/liquor-tree#62]
I'm trying to increase my AdminLTE 3 dashboard with liquor-tree. In order to keep original template I'd like to ask if is it possible to change position and style of tree-arrow.

Example of demo dashboard:
![image](https://user-images.githubusercontent.com/7257227/47591502-3b433b00-d946-11e8-8d87-bd6425abb702.png)

**Comment by amsik** [comment]
Hi! 

Yes, it is very easy to change the position. You need to add a css property:

```css
 .tree-content {
   flex-direction: row-reverse;
 }
```

Also to add badgets check [this link](https://amsik.github.io/liquor-tree/#Custom-Node)

**Comment by marcosrocha85** [comment]
@amsik Thank you very much. :smiley:

**Comment by georginklv** [comment]
Hello is it possible to change just the arrow position without the checkbox ?
