### ISSUE TITLE
Best way to make two synced trees

### ISSUE THREAD

**Issue by tinboyko** [amsik/liquor-tree#65]
In my case I need to make pinned files functionality. Pinned files must be at the top of tree and they must be synced with original. For example: when i rename pinned file, original file will be renamed too and etc. Maybe we can make it like one of liquor-tree feature.

**Comment by amsik** [comment]
Interesting idea. But you can do it now. 

1. Clone the repo
2. `npm run dev`
3. Open `Exporting` page
