### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by Diaskhan** [amsik/liquor-tree#7]
Thank U for component!

Is there some api or documentation to use icons?

For example I creating hieararchy Filesystem via web app! A need icons for folders, and need icons for my entities 
![image](https://user-images.githubusercontent.com/15046677/38404052-35458634-3989-11e8-8d45-6ee28c30ef3c.png)

**Comment by amsik** [comment]
Hi! Thanks!

Yes, you're able to customize a node. See [example](https://jsfiddle.net/amsik/06x8nb9c/)

To customize the arrow you need to use css styles. VueJS is not supporting deeper named scopes, that's why we cannot use named scopes for each part of node.

**Comment by Diaskhan** [comment]
Maybe this need add to documentation ??
Could be some items with with different icons not with the same ??

**Comment by amsik** [comment]
We already have example: [doc](https://amsik.github.io/liquor-tree/#Radio). It seemed to me that it would be understandable. But it is not. I will add more examples to the documentation.

Yes, I have plans to add abillity to filter tree. It will be done within 1-2 days.

**Comment by Diaskhan** [comment]
If u plan add filter functionality ! 
A have a few ideas how filter tree! 
If u interested let me know !

**Comment by amsik** [comment]
Yes, I'm open to any ideas. I've raised a new [issue](https://github.com/amsik/liquor-tree/issues/8) for this. Welcome :)

**Comment by 3snit** [comment]
We are now June 2020 ... 
Just want to thank you for this awesome component.

Kind regards,
Johnny
Belgium
