### ISSUE TITLE
How to reload tree?

### ISSUE THREAD

**Issue by sergpy** [amsik/liquor-tree#70]
The approach in https://github.com/amsik/liquor-tree/issues/9 works:
 this.$refs.tree.tree.setModel(items);

but only once
How to reload tree many times?

**Comment by amsik** [comment]
Fixed in commit [54a0b5c45a8df503075bd1a3fefe3e065b51042d](https://github.com/amsik/liquor-tree/commit/54a0b5c45a8df503075bd1a3fefe3e065b51042d). It will be available via npm in the evening.

**Comment by sergpy** [comment]
works, but for root nodes only
all children lost, and children list is empty on expand

**Comment by amsik** [comment]
Could you show me an example?

**Comment by sergpy** [comment]
yes, try  https://jsfiddle.net/sergpy/m8xuyrfb/6/
- Click reload (twice), 
- then change root order  (A <--> B)
- expand Root B
it is empty

**Comment by amsik** [comment]
Yes, this is a problem. Now it’s not quite clear where to insert a node. I'm working on it

**Comment by alicompu** [comment]
I'm worked 
reload data 
if (catesCurrentYearCost.length)                
                this.treeViewData[0].children[1].children =  this.convert(catesCurrentYearCost, true);

            this.$refs.tree.tree.setModel(this.treeViewData)
