### ISSUE TITLE
Is there a way to unselect all nodes?

### ISSUE THREAD

**Issue by grofit** [amsik/liquor-tree#73]
I have a situation where I have a workspace where users can select visual elements and I want those to update the selection in the tree, and vice versa. However at the moment every time someone selects an element in the view the tree does update its selection but doesnt unselect the previous one so is there a built in way to be able to clear all selections or just get current selection and unselect it?

**Comment by amsik** [comment]
Hi. Yes, you have many ways to do it:

```javascript
const tree = this.$refs.tree

tree.unselectAll()
tree.selected().unselect()
tree.selectAll()

// the same with `check` state
```

**Comment by grofit** [comment]
ah brilliant, is this in the docs? as I couldnt find it anywhere.

**Comment by amsik** [comment]
No :(   I will create an issue to do it.
