### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by amsik** [amsik/liquor-tree#8]
Add an opportunity to filter tree.

**Comment by Diaskhan** [comment]
Here scenario number 1 
![image](https://user-images.githubusercontent.com/15046677/38434089-f40f3596-39ee-11e8-9220-942fa5a9ce67.png)

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/38434444-29991776-39f0-11e8-9529-05430ddb54a5.png)

**Comment by amsik** [comment]
Agree with you. I'm working on it already. 
About the last one... We will have a function which checks by condition. Something like this:

```javascript
{
  filter: function(term, node) {
    return node.data.number > term
  }
}
```

**Comment by amsik** [comment]
Working on the 2th scenario

**Comment by Diaskhan** [comment]
U could use https://github.com/bevacqua/fuzzysearch
It is Fast and Fourious )))

**Comment by amsik** [comment]
I'm trying to do the library as easy as it possible. We have an opportunity to override the **matcher** function.

```javascript
...
options: {
  filter: {
    matcher(query, node) {
       
    }
  }
}
...
```

Maybe in the future we will be able to switch some option to highlight the matched text. I hope at an early future :)

**Comment by Diaskhan** [comment]
Early future ))))
Please look at  https://vue-treeselect.js.org/  his got good functional!

**Comment by amsik** [comment]
Okay :)  I will check.

**Comment by Diaskhan** [comment]
Could u include this new functional in documentation ?

**Comment by Diaskhan** [comment]
And how to use it !

**Comment by amsik** [comment]
Yes. I'm planning to do it today and add more demos

**Comment by Diaskhan** [comment]
What do u think about drag n drop functionalyti ?

**Comment by amsik** [comment]
I have created a new [issue](https://github.com/amsik/liquor-tree/issues/11)

**Comment by amsik** [comment]
- you can clone the repository and run commands:
 `npm install`
 `npm run dev`

- https://jsfiddle.net/amsik/o7v4a2nL/

**Comment by Diaskhan** [comment]
Ahhhh it's awesome good. It's very Awesome, Dude u Make my day )))))))))

**Comment by amsik** [comment]
I very happy to help you :)

**Comment by VPihalov** [comment]
Hi! Thank U for the awesome lib.
But where I can add filter options with emptyText in the tree stucture in order to change "Nothing found!" to my other message?
