### ISSUE TITLE
Vuex change data

### ISSUE THREAD

**Issue by nlefebvre1410** [amsik/liquor-tree#81]
hi,
the problem is when changing green updateTree gives them change ex:
[{"id": 1, "text": "Requests", "text": "Requests", "state": {"editable": false}, "children": transforts:
[{"text": "Requests", "data": {"text": "Requests"}, "state": {"selected": false, "selectable": true, "checked": false, " expanded ": true," disabled ": false," visible ": true," indeterminate ": false," matched ": false," editable ": false," dragging ": false," draggable ": true," dropable " : true}, "children":
we see that ID has disappeared

**Comment by amsik** [comment]
Hi!

Could you please show me a real example? How do you call the `updateTree`?

**Comment by nlefebvre1410** [comment]
yes
the code vuejs:

`import LiquorTree from 'liquor-tree'
import {mapGetters} from 'vuex'
import store from '@/store'

export default {

  data () {
    return {

      nodeid: 1,
      treeOptions: {
        store: {
          store: this.$store,
          // key: 'tree',
          getter: () => {
            return this.getTypeDate
          },
          dispatcher (tree) {
            store.dispatch('updateTree', tree)
          }
        },
        checkbox: true
      }
    }
  },
  components: {
    tree: LiquorTree
  },
  computed: {
    ...mapGetters([
      'getTypeDate',
      'getLoading'
    ])
  },`

this code vuex:
Action:
`export const updateTree = ({commit, state}, payload) => {
  commit('setTypeTree', payload)
}`
mutations:
`export const setTypeTree = (state, data) => {
  state.typeData = data
}`

**Comment by amsik** [comment]
Hi. Yes, I've found the bug too. Could you please try story _your_ node in in `data` property. I will not be changed. I will raise a new issue

**Comment by nlefebvre1410** [comment]
ok
