### ISSUE TITLE
Could you add key down event on tree?

### ISSUE THREAD

**Issue by sjquant** [amsik/liquor-tree#82]
Thanks for this awesome library.

I want to make tree editable when I key down F2.

Is there any way? or Could you add it?

**Comment by amsik** [comment]
As I understand you want to edit **selected** node when you key down F2. It is easy to do it via your own keydown event (native one).  For instance:

```html
  <div id="app" @keydown="onKeyDown">
      <tree
          ref="tree"      
          :data="treeData"
        />
  </div>
```

```javascript
 onKeyDown(e) {
  if (F2_is_pressed) {
    const selected = this.$refs.tree.selected() // it might be more than 1 selected node

    if (selected) {
      selected.startEditing()
    }
  }
 }
```

**Comment by sjquant** [comment]
Thank you for your answer!
