### ISSUE TITLE
Close same level node when opening one

### ISSUE THREAD

**Issue by CesarDINDELEUX** [amsik/liquor-tree#84]
Hi, first of all thanks for your amazing plugin.

I was wondering if it was possible to close same level node when opening one ? 

Example

Node 1 is open
Click on Node 2 (same level as Node 1)
Node 1 get closed
Node 2 is opening

Thanks.

**Comment by kl3sk** [comment]
I think you can rely on the [Selection API](https://amsik.github.io/liquor-tree/#Selection-API)

**Comment by amsik** [comment]
Hi! Thanks for using the library :)

Here is an example: https://jsfiddle.net/amsik/p8mqhng2/

**Comment by kl3sk** [comment]
It doen't work [this way](https://jsfiddle.net/klesk/mLt0jays/)

**Comment by kl3sk** [comment]
Yes thanks. I didn't see the `depth` property.

**Comment by CesarDINDELEUX** [comment]
> It is just example. Also you can check `depth` property. Check again: https://jsfiddle.net/amsik/p8mqhng2/

Thanks ! I will definitly try that ! :D

**Comment by amsik** [comment]
You are welcome! :)

**Comment by CesarDINDELEUX** [comment]
Here is the code for collapsing childs when collapsing parent , might be usefull for someone one day :) 

```
onNodeCollapse(node){ // Fermer les enfant quand les parents sont fermés.
        const expandedNodes = this.$refs.tree.findAll({state : {expanded: true}})
        if (expandedNodes != null){
        expandedNodes.forEach(expandedNode => {
          if(expandedNode.parent.id == node.id) {
            expandedNode.collapse()
          }
        })
        }
    }
```

**Comment by kl3sk** [comment]
Maybe these examples could be added to the doc ?

**Comment by amsik** [comment]
Added.
