### ISSUE TITLE
Eddit tree style

### ISSUE THREAD

**Issue by CesarDINDELEUX** [amsik/liquor-tree#87]
Hey guys, is it possible to edit the style of trees ? 

Like the padding between child and parents, putting parent in BOLD, distance between arrow and text etc ? I've tried few things but my css skill is beyond null ! 

Managed to edit the font size with : 
```
.tree-anchor {
  font-size: 12px;
}
```
But as soon I try anything with childs I'm kinda stuck.

Thanks a lot !

**Comment by amsik** [comment]
Hi! Check this example: https://amsik.github.io/liquor-tree/#Custom-Theme

**Comment by opowell** [comment]
Works fine for me. For example, you can change the selected node color:     
```
.tree-node.selected > .tree-content > .tree-anchor {
    color: blue;
}
```

**Comment by georginklv** [comment]
How can i change the style of the arrow ?
