### ISSUE TITLE
The model object in component data does not react to the changes of the data prop, resulting in bizaar behavior

### ISSUE THREAD

**Issue by tobunka-git** [amsik/liquor-tree#9]
I have deployed the liquor-tree component and found that any changes to the data prop do not affect the model object in component data.

Specifically, I have my code to compose two sets of tree data in terms of different languages. While I changed the tree data from a language to another by passing a different object as the data prop, the liquor tree is totally not affected.

After reading the source code, I assume that the tree data passed into the data prop is just an intermediate object. However, the model object in the component data, which is calculated based on the data prop, is the actual source of the tree.

Based on the assumption, a mechanism that watches the data prop changes is required.

**Comment by Diaskhan** [comment]
Yess, when I load data via computed, it doesnt react !

<script>
    const app = new Vue({
        el: '#app',
        data: function () {
            return {
                treeData: getTreeData()
            }
        },
        mounted: function () {
            this.buildtree();
        },
        methods: {
            onNodeSelected(node) {
                console.log(node.text, node)
            },

            buildtree: function () {
                var self = this;
                axios.get("/ProcessDesigner/BuildTree")
                    .then(response => {
                        self.treeData = response.data;
                        //self.selected = 0;
                        //alert(self.selected);
                    })

            }
        },


    })

    function getTreeData() {
        return [

            //{
            //  text: 'Vehicles', state: { expanded: true }, children: [
            //    { text: 'ALFA ROMEO', state: { expanded: true }, data: {vehicleGroup: 'alfa-romeo'}, children: [
            //      { text: '155' },
            //      { text: '159' },
            //      { text: '164' },
            //      { text: 'Guilietta' }
            //    ] },
            //    { text: 'Audi', data: {vehicleGroup: 'audi'}, children: [
            //      { text: 'A4' },
            //      { text: 'A5' },
            //      { text: 'A6' },
            //      { text: 'A8' },
            //      { text: 'Q7' }
            //    ] },
            //    { text: 'BMW', data: {vehicleGroup: 'bmw'}, children: [
            //      { text: 'X3' },
            //      { text: 'X4' },
            //      { text: 'X5' },
            //      { text: 'X6' }
            //    ] }
            //  ]
            //}
        ]
    }
</script>

**Comment by tobunka-git** [comment]
oh, forgive me not turn to the closed issues. thanks for pointing it out, and i'll have a try.
please be so kind to close this issue. thanks.

**Comment by Diaskhan** [comment]
Yes workaround is works for me !

**<body>
    <div class="page-header">
        <h2>@ViewData["Title"]</h2>
    </div>
    <div id="app">
        <tree :data="treeData" ref="tree" class="vehicle-tree" @@node:selected="onNodeSelected">
            <label class="tree-text vehicle-label" slot-scope="{ node }">
                <template v-if="node.isfolder">
                    <i class="icon-doc"></i>
                    {{ node.text }}
                </template>

                <template v-else>
                    <i :class="node.expanded() ? 'icon-folder-alt' : 'icon-folder'"></i>
                    {{ node.text }}
                </template>
            </label>
        </tree>
    </div>
</body>
<script>
    const app = new Vue({
        el: '#app',
        data: function () {
            return {
                treeData: getTreeData()
            }
        },
        mounted: function () {
            this.buildtree();
        },
        methods: {
            onNodeSelected(node) {
                console.log(node.text, node)
            },

            buildtree: function () {
                const tree = this.$refs.tree.tree
                var self = this;
                axios.get("/ProcessDesigner/BuildTree")
                    .then(response => {
                        self.treeData = response.data;
                        let model = tree.parse(self.treeData);
                        this.$set(this.$refs.tree, 'model', model);
                        tree.setModel(model);
                    })

            }
        },
    })

    function getTreeData() {
        return [   ]
            }
        ]
    }**

**Comment by Diaskhan** [comment]
tobunka-git U can close issue by yourself, it standart option of github !

**Comment by GerryLon** [comment]
@Diaskhan , I want to know how to keep the tree ui state(like expanded or selected etc.).

code from your comment will lose the ui state
```javascript
self.treeData = response.data;
let model = tree.parse(self.treeData);
this.$set(this.$refs.tree, 'model', model);
tree.setModel(model);
```

Can you help me? 
Many thanks!

**Comment by amsik** [comment]
Please check the example:
- clone this repo
- `npm install`
- `npm run dev`
- open `Vuex Intergation` page

There you will find, that I do not overriding the `model`. You can do it either on **initialization** stage or to **override** the model.

In your case you have to check which node you should update

**Comment by GerryLon** [comment]
Your example can work properly! But my condition is a bit different.
In one word, I just want to change tree data like the way below and do not lose the UI state:
```javascript
this.$refs.tree.tree.setModel(newTreeData);
```

Many Thanks!

**Comment by PatBriPerso** [comment]
The workaround https://jsfiddle.net/amsik/b61h6wxk/10/ does not work properly: it load the tree elements but it does not apply the 'state' property of each element. 

This new version: https://jsfiddle.net/b61h6wxk/27/ applies the 'state' property.

I just comment the last line: 
``` javascript
let model = tree.parse(data)
this.$set(this.$refs.someTree, 'model', model)
// tree.setModel(model)
```

If you watch carefully you will see that the 'selected' state is not applied. I think it is due to this part of the code:
``` javascript
    // Nodes can't be selected on init. By it's possible to select through API
    if (this.options.checkOnSelect && this.options.checkbox) {
      this.unselectAll()
    }
```

**Comment by amsik** [comment]
Try new version: [https://jsfiddle.net/amsik/b61h6wxk/29/](https://jsfiddle.net/amsik/b61h6wxk/29/)
