### ISSUE TITLE
prevent selecting a node when you drag and release mouse button over top a node

### ISSUE THREAD

**Issue by JasonHenson** [amsik/liquor-tree#91]
Is it possible to prevent node selection when you hold down the right mouse button outside of the tree and drag over top a node and release the mouse button? 

The reason I ask is because we have a forms to the right of our tree view and its common to drag mouse to highlight text in a field (to delete the text), but if you accidentally release your mouse over top of a tree node -- a different node will be selected. So, this is basically an annoyance for the user in our particular situation.

**Comment by JasonHenson** [comment]
What event are you using when a node is selected in the tree? Is it mouse up?

**Comment by amsik** [comment]
Hi. For selecting i'm using `mouseUp` event.  The same event for checking. Could you show me your example? Maybe I can help you

**Comment by JasonHenson** [comment]
The issue is when you hold down your mouse down, for example, copying some text beside the tree view, and  you accidentally release your mouse over the tree view --  it will change the node.  Any reason you couldn't change to mouse down event instead?

**Comment by amsik** [comment]
Agree. In case of async loading the child it will call immediately. So `mousedown` is not good.
