### ISSUE TITLE
Question: Execute code before node selection?

### ISSUE THREAD

**Issue by ml-eds** [amsik/liquor-tree#99]
Thanks for the great component!

Is it possible to hook into a "beforeSelection" event to execute code before the selection of a node? And also cancel the selection if certain conditions are not met?

In our use case, for example, a new selection should only be allowed and executed if a save operation based on previsiously selected node succeeds.

**Comment by amsik** [comment]
Hi! Yeah, it is a great idea. I'll add it today.

**Comment by ml-eds** [comment]
Thanks for providing the fiddle. Together with @node:unselected I should be able to build sth. which keeps or restores the previous selection.
